name: reusable-ci

on:
  workflow_call:
    inputs:
      sonar_project_key:
        required: false
        type: string
      sonar_organization:
        required: false
        type: string
      enable_sonar:
        required: false
        type: boolean
        default: false
      enable_jacoco:
        required: false
        type: boolean
        default: false
      coverage_threshold:
        required: false
        type: number
        default: 70
    secrets:
      SONAR_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests (no coverage)
        if: ${{ !inputs.enable_jacoco }}
        run: mvn -B -ntp test

      - name: Run tests with JaCoCo
        if: ${{ inputs.enable_jacoco }}
        run: |
          mvn -B -ntp \
            -DskipITs=true \
            test jacoco:report

      - name: Upload Surefire reports on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: "**/target/surefire-reports/**/*"

      - name: Upload JaCoCo report
        if: ${{ inputs.enable_jacoco }}
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

  quality-gate:
    if: ${{ inputs.enable_jacoco }}
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: jacoco

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Validate test coverage
        env:
          THRESHOLD: ${{ inputs.coverage_threshold }}
        run: |
          set -euo pipefail
          REPORT="jacoco/jacoco.xml"

          if [ ! -f "$REPORT" ]; then
            echo "❌ Coverage report not found at $REPORT"
            exit 1
          fi

          LINE_COVERED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" "$REPORT")
          LINE_MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" "$REPORT")

          TOTAL=$((LINE_COVERED + LINE_MISSED))
          if [ "$TOTAL" -eq 0 ]; then
            echo "❌ No lines found in the JaCoCo report. Failing..."
            exit 1
          fi

          # integer percentage
          PERCENT=$(( 100 * LINE_COVERED / TOTAL ))
          echo "ℹ️ Total line coverage: $PERCENT% ($LINE_COVERED/$TOTAL)"

          if [ "$PERCENT" -lt "$THRESHOLD" ]; then
            echo "❌ Code coverage is $PERCENT%, below threshold ${THRESHOLD}%"
            exit 1
          else
            echo "✅ Code coverage is $PERCENT%, meets threshold ${THRESHOLD}%"
          fi

  code-analysis:
    if: ${{ inputs.enable_sonar && ( !inputs.enable_jacoco || needs.quality-gate.result == 'success' ) }}
    needs: [unit-test, quality-gate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -ntp verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=${{ inputs.sonar_project_key }} \
            -Dsonar.organization=${{ inputs.sonar_organization }}
